// Generated by view binder compiler. Do not edit!
package com.example.filmapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.filmapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button btnAddFilm;

  @NonNull
  public final Button btnSelectImage;

  @NonNull
  public final EditText etFilmDesc;

  @NonNull
  public final EditText etFilmName;

  @NonNull
  public final RecyclerView rvFilms;

  private ActivityMainBinding(@NonNull LinearLayout rootView, @NonNull Button btnAddFilm,
      @NonNull Button btnSelectImage, @NonNull EditText etFilmDesc, @NonNull EditText etFilmName,
      @NonNull RecyclerView rvFilms) {
    this.rootView = rootView;
    this.btnAddFilm = btnAddFilm;
    this.btnSelectImage = btnSelectImage;
    this.etFilmDesc = etFilmDesc;
    this.etFilmName = etFilmName;
    this.rvFilms = rvFilms;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnAddFilm;
      Button btnAddFilm = ViewBindings.findChildViewById(rootView, id);
      if (btnAddFilm == null) {
        break missingId;
      }

      id = R.id.btnSelectImage;
      Button btnSelectImage = ViewBindings.findChildViewById(rootView, id);
      if (btnSelectImage == null) {
        break missingId;
      }

      id = R.id.etFilmDesc;
      EditText etFilmDesc = ViewBindings.findChildViewById(rootView, id);
      if (etFilmDesc == null) {
        break missingId;
      }

      id = R.id.etFilmName;
      EditText etFilmName = ViewBindings.findChildViewById(rootView, id);
      if (etFilmName == null) {
        break missingId;
      }

      id = R.id.rvFilms;
      RecyclerView rvFilms = ViewBindings.findChildViewById(rootView, id);
      if (rvFilms == null) {
        break missingId;
      }

      return new ActivityMainBinding((LinearLayout) rootView, btnAddFilm, btnSelectImage,
          etFilmDesc, etFilmName, rvFilms);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
