// Generated by view binder compiler. Do not edit!
package com.example.filmapp.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.filmapp.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ItemFilmBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView imgFilm;

  @NonNull
  public final TextView tvFilmDesc;

  @NonNull
  public final TextView tvFilmName;

  private ItemFilmBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView imgFilm,
      @NonNull TextView tvFilmDesc, @NonNull TextView tvFilmName) {
    this.rootView = rootView;
    this.imgFilm = imgFilm;
    this.tvFilmDesc = tvFilmDesc;
    this.tvFilmName = tvFilmName;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ItemFilmBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ItemFilmBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.item_film, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ItemFilmBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imgFilm;
      ImageView imgFilm = ViewBindings.findChildViewById(rootView, id);
      if (imgFilm == null) {
        break missingId;
      }

      id = R.id.tvFilmDesc;
      TextView tvFilmDesc = ViewBindings.findChildViewById(rootView, id);
      if (tvFilmDesc == null) {
        break missingId;
      }

      id = R.id.tvFilmName;
      TextView tvFilmName = ViewBindings.findChildViewById(rootView, id);
      if (tvFilmName == null) {
        break missingId;
      }

      return new ItemFilmBinding((ConstraintLayout) rootView, imgFilm, tvFilmDesc, tvFilmName);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
